"""empty message

Revision ID: 9ed5cc91b215
Revises: e96865e4fa62
Create Date: 2024-02-14 23:49:10.158857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ed5cc91b215'
down_revision = 'e96865e4fa62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessons',
    sa.Column('l_id', sa.Integer(), nullable=False),
    sa.Column('lesson', sa.String(length=350), nullable=True),
    sa.PrimaryKeyConstraint('l_id'),
    sa.UniqueConstraint('lesson')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lessons')
    # ### end Alembic commands ###
